### PR TITLE
Allow access to mounted disks

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by soredake** [comment]
@eszlari

**Comment by soredake** [comment]
@barthalion

**Comment by soredake** [comment]
@KuSh

**Comment by KuSh** [comment]
I think we should restrict filesystems to xdg-dowload and xdg-run/gvfs as documented

**Comment by soredake** [comment]
@KuSh i tried gvfs, and i see two problems:
1) gvfs is not preinstalled on kde-based distros
2) it does not work (on kde, at least) as jdownloader is not gvfs-aware

When i give access to /run/media and /media i see my disks:
изображение

**Comment by KuSh** [comment]
Ok I'll try your PR on gnome to see how it works later today !

**Comment by KuSh** [comment]
This is working in Gnome too. Thanks!

**Pull request merged**
